// Auto-generated by build.rs. DO NOT EDIT.

/** A tool call that is currently in progress. */
export interface ActiveTool {
  detail?: string;
  failure_detail?: string;
  key: ToolKey;
  name: string;
}

export type AgentData =
  { active_tools: ActiveTool[] | undefined; agent_id: string | undefined; event_emoji: string; failure_detail: string | undefined; hook_event_name: string; recent_tools: ActiveTool[] | undefined; session_id: string | undefined; status: AgentStatus; tool_detail: string | undefined; tool_name: string | undefined; type: "claude" } |
  { active_tools: ActiveTool[] | undefined; event_emoji: string | undefined; event_type: string | undefined; is_busy: boolean | undefined; recent_tools: ActiveTool[] | undefined; session_id: string | undefined; status: AgentStatus; tool_detail: string | undefined; tool_name: string | undefined; type: "opencode" } |
  { active_tools: ActiveTool[] | undefined; agent_id: string | undefined; agent_type: string | undefined; cwd: string | undefined; event_emoji: string; failure_detail: string | undefined; hook_event_name: string; model: string | undefined; permission_mode: string | undefined; recent_tools: ActiveTool[] | undefined; session_id: string | undefined; status: AgentStatus; tool_detail: string | undefined; tool_name: string | undefined; transcript_path: string | undefined; turn_id: string | undefined; type: "codex" };

export type AgentStatus = "started" | "running" | "waiting" | "permission" | "ended";

export type ToolKey =
  { tool_use_id: string; type: "claude" } |
  { tool_use_id: string; type: "codex" } |
  { detail: string | undefined; name: string; type: "opencode" };

/** Top-level agent state tracked by the TUI. */
export interface AgentState {
  data: AgentData;
  tmux_pane: string;
  updated_at: number;
}

