use std::collections::BTreeMap;
use std::path::Path;

use schemars::schema::{InstanceType, RootSchema, Schema, SchemaObject, SingleOrVec};
use schemars::schema_for;

fn main() {
    generate_contract();
    println!("cargo:rerun-if-changed=build.rs");
}

fn generate_contract() {
    let schema: RootSchema = schema_for!(chikuwa_types::state::AgentState);
    let schema_json = serde_json::to_string_pretty(&schema).unwrap();

    let workspace_root = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .to_path_buf();

    // Generate JSON Schema
    let schema_path = workspace_root.join("schemas/opencode-protocol.json");
    if should_write(&schema_path, &schema_json) {
        std::fs::write(&schema_path, &schema_json).unwrap();
        println!("cargo:warning=Generated opencode-protocol.json");
    }

    // Generate TypeScript
    let ts_types = generate_typescript_types(&schema);
    let ts_path = workspace_root.join("plugins/opencode-types.ts");
    if should_write(&ts_path, &ts_types) {
        std::fs::write(&ts_path, &ts_types).unwrap();
        println!("cargo:warning=Generated plugins/opencode-types.ts");
    }
}

fn should_write(path: &Path, content: &str) -> bool {
    std::fs::read_to_string(path).is_ok_and(|existing| existing != content) || !path.exists()
}

fn generate_typescript_types(schema: &RootSchema) -> String {
    let mut out = String::new();
    out.push_str("// Auto-generated by build.rs. DO NOT EDIT.\n\n");

    let mut def_names: Vec<&String> = schema.definitions.keys().collect();
    def_names.sort();
    for name in def_names {
        if let Some(def) = schema.definitions.get(name) {
            if let Some(ts) = definition_to_typescript(name, def, &schema.definitions) {
                out.push_str(&ts);
            }
        }
    }

    let root_obj = Schema::Object(schema.schema.clone());
    if let Some(ts) = interface_from_schema("AgentState", &root_obj, &schema.definitions) {
        out.push_str(&ts);
    }

    out
}

fn definition_to_typescript(
    name: &str,
    schema: &Schema,
    defs: &BTreeMap<String, Schema>,
) -> Option<String> {
    match schema {
        Schema::Object(obj) => {
            if has_enum_values(obj) {
                let variants: Vec<&str> = obj
                    .enum_values
                    .as_ref()
                    .unwrap()
                    .iter()
                    .filter_map(|v| v.as_str())
                    .collect();
                let union = variants
                    .iter()
                    .map(|v| format!("\"{}\"", v))
                    .collect::<Vec<_>>()
                    .join(" | ");
                return Some(format!("export type {} = {};\n\n", name, union));
            }

            if let Some(sv) = &obj.subschemas {
                if let Some(one_of) = &sv.one_of {
                    return oneof_to_union(name, one_of, defs);
                }
            }

            if obj.object.is_some() {
                return interface_from_schema(name, schema, defs);
            }

            None
        }
        Schema::Bool(_) => None,
    }
}

fn oneof_to_union(
    name: &str,
    one_of: &[Schema],
    defs: &BTreeMap<String, Schema>,
) -> Option<String> {
    let variants: Vec<String> = one_of
        .iter()
        .filter_map(|s| {
            let t = resolve_type(s, defs);
            if t.is_empty() {
                None
            } else {
                Some(t)
            }
        })
        .collect();

    if variants.is_empty() {
        return None;
    }

    if variants.len() == 1 {
        return Some(format!("export type {} = {};\n\n", name, variants[0]));
    }

    Some(format!(
        "export type {} =\n  {};\n\n",
        name,
        variants.join(" |\n  ")
    ))
}

fn interface_from_schema(
    name: &str,
    schema: &Schema,
    defs: &BTreeMap<String, Schema>,
) -> Option<String> {
    let obj = match schema {
        Schema::Object(o) => o,
        _ => return None,
    };

    let ov = obj.object.as_ref()?;

    let mut out = String::new();

    if let Some(desc) = obj.metadata.as_ref().and_then(|m| m.description.as_deref()) {
        out.push_str(&format!("/** {} */\n", desc));
    }

    out.push_str(&format!("export interface {} {{\n", name));

    let mut props: Vec<(&String, &Schema)> = ov.properties.iter().collect();
    props.sort_by(|a, b| a.0.cmp(b.0));
    for (prop_name, prop_schema) in &props {
        let required = ov.required.contains(*prop_name);
        let ts_type = resolve_type(prop_schema, defs);
        if ts_type.is_empty() {
            continue;
        }
        out.push_str(&format!(
            "  {}{}: {};\n",
            prop_name,
            if required { "" } else { "?" },
            ts_type
        ));
    }

    out.push_str("}\n\n");
    Some(out)
}

fn has_enum_values(obj: &SchemaObject) -> bool {
    obj.enum_values.as_ref().is_some_and(|v| !v.is_empty())
}

fn resolve_type(schema: &Schema, defs: &BTreeMap<String, Schema>) -> String {
    match schema {
        Schema::Object(obj) => resolve_object_type(obj, defs),
        Schema::Bool(_) => "unknown".to_string(),
    }
}

fn resolve_object_type(obj: &SchemaObject, defs: &BTreeMap<String, Schema>) -> String {
    if let Some(ref_path) = &obj.reference {
        let name = ref_path.strip_prefix("#/definitions/").unwrap_or(ref_path);
        return name.to_string();
    }

    if let Some(enum_values) = &obj.enum_values {
        let variants: Vec<&str> = enum_values.iter().filter_map(|v| v.as_str()).collect();
        if !variants.is_empty() {
            if variants.len() == 1 {
                return format!("\"{}\"", variants[0]);
            }
            return variants
                .iter()
                .map(|v| format!("\"{}\"", v))
                .collect::<Vec<_>>()
                .join(" | ");
        }
    }

    if obj.const_value.is_some() {
        return String::new();
    }

    if let Some(sv) = &obj.subschemas {
        if let Some(one_of) = &sv.one_of {
            let types: Vec<String> = one_of
                .iter()
                .filter_map(|s| {
                    let t = resolve_type(s, defs);
                    if t.is_empty() {
                        None
                    } else {
                        Some(t)
                    }
                })
                .collect();
            if types.is_empty() {
                return String::new();
            }
            if types.len() == 1 {
                return types.into_iter().next().unwrap();
            }
            return types.join(" | ");
        }
    }

    if let Some(ov) = &obj.object {
        if ov.properties.is_empty() {
            return "Record<string, unknown>".to_string();
        }
        let mut fields: Vec<String> = Vec::new();
        let mut props: Vec<(&String, &Schema)> = ov.properties.iter().collect();
        props.sort_by(|a, b| a.0.cmp(b.0));
        for (prop_name, prop_schema) in &props {
            let required = ov.required.contains(*prop_name);
            let pt = resolve_type(prop_schema, defs);
            if pt.is_empty() {
                continue;
            }
            fields.push(format!(
                "{}: {}{}",
                prop_name,
                pt,
                if required { "" } else { " | undefined" }
            ));
        }
        return format!("{{ {} }}", fields.join("; "));
    }

    let type_name = match &obj.instance_type {
        Some(SingleOrVec::Single(t)) => match t.as_ref() {
            InstanceType::String => "string",
            InstanceType::Integer | InstanceType::Number => "number",
            InstanceType::Boolean => "boolean",
            InstanceType::Array => {
                if let Some(av) = &obj.array {
                    if let Some(items) = &av.items {
                        let inner = match items {
                            SingleOrVec::Single(s) => resolve_type(s.as_ref(), defs),
                            SingleOrVec::Vec(v) => {
                                let resolved: Vec<String> = v
                                    .iter()
                                    .map(|s| resolve_type(s, defs))
                                    .filter(|s| !s.is_empty())
                                    .collect();
                                resolved.join(" | ")
                            }
                        };
                        return format!("{}[]", inner);
                    }
                }
                "unknown[]"
            }
            _ => "unknown",
        },
        Some(SingleOrVec::Vec(types)) => {
            let resolved: Vec<String> = types
                .iter()
                .filter_map(|t| {
                    let name = match t {
                        InstanceType::String => "string",
                        InstanceType::Integer | InstanceType::Number => "number",
                        InstanceType::Boolean => "boolean",
                        _ => return None,
                    };
                    Some(name.to_string())
                })
                .collect();
            if resolved.is_empty() {
                "unknown"
            } else {
                return resolved.join(" | ");
            }
        }
        None => "unknown",
    };

    type_name.to_string()
}
